name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-library-and-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-library
        working-directory: ./ancient-clj
        run: lein test
      - name: install-library
        working-directory: ./ancient-clj
        run: lein install
      - name: test-plugin
        working-directory: ./lein-ancient
        run: lein isolate test
