name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  test-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-tests
        working-directory: ./ancient-clj
        run: lein test

  test-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install-library
        working-directory: ./ancient-clj
        run: lein install
      - name: run-tests
        working-directory: ./lein-ancient
        run: lein test
